// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages/tree.proto

package messages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Insert struct {
	Key                  int32    `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Insert) Reset()         { *m = Insert{} }
func (m *Insert) String() string { return proto.CompactTextString(m) }
func (*Insert) ProtoMessage()    {}
func (*Insert) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f49c725db8f5213, []int{0}
}

func (m *Insert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Insert.Unmarshal(m, b)
}
func (m *Insert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Insert.Marshal(b, m, deterministic)
}
func (m *Insert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Insert.Merge(m, src)
}
func (m *Insert) XXX_Size() int {
	return xxx_messageInfo_Insert.Size(m)
}
func (m *Insert) XXX_DiscardUnknown() {
	xxx_messageInfo_Insert.DiscardUnknown(m)
}

var xxx_messageInfo_Insert proto.InternalMessageInfo

func (m *Insert) GetKey() int32 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *Insert) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Delete struct {
	Key                  int32    `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Delete) Reset()         { *m = Delete{} }
func (m *Delete) String() string { return proto.CompactTextString(m) }
func (*Delete) ProtoMessage()    {}
func (*Delete) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f49c725db8f5213, []int{1}
}

func (m *Delete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Delete.Unmarshal(m, b)
}
func (m *Delete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Delete.Marshal(b, m, deterministic)
}
func (m *Delete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Delete.Merge(m, src)
}
func (m *Delete) XXX_Size() int {
	return xxx_messageInfo_Delete.Size(m)
}
func (m *Delete) XXX_DiscardUnknown() {
	xxx_messageInfo_Delete.DiscardUnknown(m)
}

var xxx_messageInfo_Delete proto.InternalMessageInfo

func (m *Delete) GetKey() int32 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *Delete) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Search struct {
	Key                  int32    `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Search) Reset()         { *m = Search{} }
func (m *Search) String() string { return proto.CompactTextString(m) }
func (*Search) ProtoMessage()    {}
func (*Search) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f49c725db8f5213, []int{2}
}

func (m *Search) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Search.Unmarshal(m, b)
}
func (m *Search) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Search.Marshal(b, m, deterministic)
}
func (m *Search) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Search.Merge(m, src)
}
func (m *Search) XXX_Size() int {
	return xxx_messageInfo_Search.Size(m)
}
func (m *Search) XXX_DiscardUnknown() {
	xxx_messageInfo_Search.DiscardUnknown(m)
}

var xxx_messageInfo_Search proto.InternalMessageInfo

func (m *Search) GetKey() int32 {
	if m != nil {
		return m.Key
	}
	return 0
}

type Traverse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Traverse) Reset()         { *m = Traverse{} }
func (m *Traverse) String() string { return proto.CompactTextString(m) }
func (*Traverse) ProtoMessage()    {}
func (*Traverse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f49c725db8f5213, []int{3}
}

func (m *Traverse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Traverse.Unmarshal(m, b)
}
func (m *Traverse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Traverse.Marshal(b, m, deterministic)
}
func (m *Traverse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Traverse.Merge(m, src)
}
func (m *Traverse) XXX_Size() int {
	return xxx_messageInfo_Traverse.Size(m)
}
func (m *Traverse) XXX_DiscardUnknown() {
	xxx_messageInfo_Traverse.DiscardUnknown(m)
}

var xxx_messageInfo_Traverse proto.InternalMessageInfo

type ScottyBeamMichHoch struct {
	Key                  int32    `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Ok                   bool     `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScottyBeamMichHoch) Reset()         { *m = ScottyBeamMichHoch{} }
func (m *ScottyBeamMichHoch) String() string { return proto.CompactTextString(m) }
func (*ScottyBeamMichHoch) ProtoMessage()    {}
func (*ScottyBeamMichHoch) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f49c725db8f5213, []int{4}
}

func (m *ScottyBeamMichHoch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScottyBeamMichHoch.Unmarshal(m, b)
}
func (m *ScottyBeamMichHoch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScottyBeamMichHoch.Marshal(b, m, deterministic)
}
func (m *ScottyBeamMichHoch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScottyBeamMichHoch.Merge(m, src)
}
func (m *ScottyBeamMichHoch) XXX_Size() int {
	return xxx_messageInfo_ScottyBeamMichHoch.Size(m)
}
func (m *ScottyBeamMichHoch) XXX_DiscardUnknown() {
	xxx_messageInfo_ScottyBeamMichHoch.DiscardUnknown(m)
}

var xxx_messageInfo_ScottyBeamMichHoch proto.InternalMessageInfo

func (m *ScottyBeamMichHoch) GetKey() int32 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *ScottyBeamMichHoch) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *ScottyBeamMichHoch) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*Insert)(nil), "messages.Insert")
	proto.RegisterType((*Delete)(nil), "messages.Delete")
	proto.RegisterType((*Search)(nil), "messages.Search")
	proto.RegisterType((*Traverse)(nil), "messages.Traverse")
	proto.RegisterType((*ScottyBeamMichHoch)(nil), "messages.scottyBeamMichHoch")
}

func init() { proto.RegisterFile("messages/tree.proto", fileDescriptor_7f49c725db8f5213) }

var fileDescriptor_7f49c725db8f5213 = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xce, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x2f, 0x29, 0x4a, 0x4d, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x80, 0x09, 0x2a, 0x19, 0x70, 0xb1, 0x79, 0xe6, 0x15, 0xa7, 0x16, 0x95, 0x08, 0x09, 0x70,
	0x31, 0x67, 0xa7, 0x56, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x81, 0x98, 0x42, 0x22, 0x5c,
	0xac, 0x65, 0x89, 0x39, 0xa5, 0xa9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x10, 0x0e, 0x48,
	0x87, 0x4b, 0x6a, 0x4e, 0x6a, 0x49, 0x2a, 0xd1, 0x3a, 0xa4, 0xb8, 0xd8, 0x82, 0x53, 0x13, 0x8b,
	0x92, 0x33, 0x30, 0x75, 0x28, 0x71, 0x71, 0x71, 0x84, 0x14, 0x25, 0x96, 0xa5, 0x16, 0x15, 0xa7,
	0x2a, 0xf9, 0x70, 0x09, 0x15, 0x27, 0xe7, 0x97, 0x94, 0x54, 0x3a, 0xa5, 0x26, 0xe6, 0xfa, 0x66,
	0x26, 0x67, 0x78, 0xe4, 0x63, 0xd3, 0x83, 0xdd, 0x16, 0x21, 0x3e, 0x2e, 0xa6, 0xfc, 0x6c, 0x09,
	0x66, 0x05, 0x46, 0x0d, 0x8e, 0x20, 0xa6, 0xfc, 0xec, 0x24, 0x36, 0xb0, 0x57, 0x8d, 0x01, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x06, 0x75, 0x7f, 0x17, 0x01, 0x01, 0x00, 0x00,
}
