// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tree.proto

package messages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Insert struct {
	Key                  int32    `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Insert) Reset()         { *m = Insert{} }
func (m *Insert) String() string { return proto.CompactTextString(m) }
func (*Insert) ProtoMessage()    {}
func (*Insert) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{0}
}

func (m *Insert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Insert.Unmarshal(m, b)
}
func (m *Insert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Insert.Marshal(b, m, deterministic)
}
func (m *Insert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Insert.Merge(m, src)
}
func (m *Insert) XXX_Size() int {
	return xxx_messageInfo_Insert.Size(m)
}
func (m *Insert) XXX_DiscardUnknown() {
	xxx_messageInfo_Insert.DiscardUnknown(m)
}

var xxx_messageInfo_Insert proto.InternalMessageInfo

func (m *Insert) GetKey() int32 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *Insert) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Search struct {
	Key                  int32    `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Search) Reset()         { *m = Search{} }
func (m *Search) String() string { return proto.CompactTextString(m) }
func (*Search) ProtoMessage()    {}
func (*Search) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{1}
}

func (m *Search) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Search.Unmarshal(m, b)
}
func (m *Search) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Search.Marshal(b, m, deterministic)
}
func (m *Search) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Search.Merge(m, src)
}
func (m *Search) XXX_Size() int {
	return xxx_messageInfo_Search.Size(m)
}
func (m *Search) XXX_DiscardUnknown() {
	xxx_messageInfo_Search.DiscardUnknown(m)
}

var xxx_messageInfo_Search proto.InternalMessageInfo

func (m *Search) GetKey() int32 {
	if m != nil {
		return m.Key
	}
	return 0
}

type Traverse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Traverse) Reset()         { *m = Traverse{} }
func (m *Traverse) String() string { return proto.CompactTextString(m) }
func (*Traverse) ProtoMessage()    {}
func (*Traverse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{2}
}

func (m *Traverse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Traverse.Unmarshal(m, b)
}
func (m *Traverse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Traverse.Marshal(b, m, deterministic)
}
func (m *Traverse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Traverse.Merge(m, src)
}
func (m *Traverse) XXX_Size() int {
	return xxx_messageInfo_Traverse.Size(m)
}
func (m *Traverse) XXX_DiscardUnknown() {
	xxx_messageInfo_Traverse.DiscardUnknown(m)
}

var xxx_messageInfo_Traverse proto.InternalMessageInfo

type ScottyBeamMichHoch struct {
	Key                  int32    `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Ok                   bool     `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScottyBeamMichHoch) Reset()         { *m = ScottyBeamMichHoch{} }
func (m *ScottyBeamMichHoch) String() string { return proto.CompactTextString(m) }
func (*ScottyBeamMichHoch) ProtoMessage()    {}
func (*ScottyBeamMichHoch) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{3}
}

func (m *ScottyBeamMichHoch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScottyBeamMichHoch.Unmarshal(m, b)
}
func (m *ScottyBeamMichHoch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScottyBeamMichHoch.Marshal(b, m, deterministic)
}
func (m *ScottyBeamMichHoch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScottyBeamMichHoch.Merge(m, src)
}
func (m *ScottyBeamMichHoch) XXX_Size() int {
	return xxx_messageInfo_ScottyBeamMichHoch.Size(m)
}
func (m *ScottyBeamMichHoch) XXX_DiscardUnknown() {
	xxx_messageInfo_ScottyBeamMichHoch.DiscardUnknown(m)
}

var xxx_messageInfo_ScottyBeamMichHoch proto.InternalMessageInfo

func (m *ScottyBeamMichHoch) GetKey() int32 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *ScottyBeamMichHoch) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *ScottyBeamMichHoch) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type Delete struct {
	Key                  int32    `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Delete) Reset()         { *m = Delete{} }
func (m *Delete) String() string { return proto.CompactTextString(m) }
func (*Delete) ProtoMessage()    {}
func (*Delete) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{4}
}

func (m *Delete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Delete.Unmarshal(m, b)
}
func (m *Delete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Delete.Marshal(b, m, deterministic)
}
func (m *Delete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Delete.Merge(m, src)
}
func (m *Delete) XXX_Size() int {
	return xxx_messageInfo_Delete.Size(m)
}
func (m *Delete) XXX_DiscardUnknown() {
	xxx_messageInfo_Delete.DiscardUnknown(m)
}

var xxx_messageInfo_Delete proto.InternalMessageInfo

func (m *Delete) GetKey() int32 {
	if m != nil {
		return m.Key
	}
	return 0
}

type DeleteResult struct {
	Successful           bool     `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResult) Reset()         { *m = DeleteResult{} }
func (m *DeleteResult) String() string { return proto.CompactTextString(m) }
func (*DeleteResult) ProtoMessage()    {}
func (*DeleteResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{5}
}

func (m *DeleteResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResult.Unmarshal(m, b)
}
func (m *DeleteResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResult.Marshal(b, m, deterministic)
}
func (m *DeleteResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResult.Merge(m, src)
}
func (m *DeleteResult) XXX_Size() int {
	return xxx_messageInfo_DeleteResult.Size(m)
}
func (m *DeleteResult) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResult.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResult proto.InternalMessageInfo

func (m *DeleteResult) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

type CheckLeftMax struct {
	MaxKey               int32    `protobuf:"varint,1,opt,name=maxKey,proto3" json:"maxKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckLeftMax) Reset()         { *m = CheckLeftMax{} }
func (m *CheckLeftMax) String() string { return proto.CompactTextString(m) }
func (*CheckLeftMax) ProtoMessage()    {}
func (*CheckLeftMax) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{6}
}

func (m *CheckLeftMax) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckLeftMax.Unmarshal(m, b)
}
func (m *CheckLeftMax) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckLeftMax.Marshal(b, m, deterministic)
}
func (m *CheckLeftMax) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckLeftMax.Merge(m, src)
}
func (m *CheckLeftMax) XXX_Size() int {
	return xxx_messageInfo_CheckLeftMax.Size(m)
}
func (m *CheckLeftMax) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckLeftMax.DiscardUnknown(m)
}

var xxx_messageInfo_CheckLeftMax proto.InternalMessageInfo

func (m *CheckLeftMax) GetMaxKey() int32 {
	if m != nil {
		return m.MaxKey
	}
	return 0
}

type BruderMussLos struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BruderMussLos) Reset()         { *m = BruderMussLos{} }
func (m *BruderMussLos) String() string { return proto.CompactTextString(m) }
func (*BruderMussLos) ProtoMessage()    {}
func (*BruderMussLos) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{7}
}

func (m *BruderMussLos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BruderMussLos.Unmarshal(m, b)
}
func (m *BruderMussLos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BruderMussLos.Marshal(b, m, deterministic)
}
func (m *BruderMussLos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BruderMussLos.Merge(m, src)
}
func (m *BruderMussLos) XXX_Size() int {
	return xxx_messageInfo_BruderMussLos.Size(m)
}
func (m *BruderMussLos) XXX_DiscardUnknown() {
	xxx_messageInfo_BruderMussLos.DiscardUnknown(m)
}

var xxx_messageInfo_BruderMussLos proto.InternalMessageInfo

type IchZiehAus struct {
	MyMax                int32    `protobuf:"varint,1,opt,name=myMax,proto3" json:"myMax,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IchZiehAus) Reset()         { *m = IchZiehAus{} }
func (m *IchZiehAus) String() string { return proto.CompactTextString(m) }
func (*IchZiehAus) ProtoMessage()    {}
func (*IchZiehAus) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{8}
}

func (m *IchZiehAus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IchZiehAus.Unmarshal(m, b)
}
func (m *IchZiehAus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IchZiehAus.Marshal(b, m, deterministic)
}
func (m *IchZiehAus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IchZiehAus.Merge(m, src)
}
func (m *IchZiehAus) XXX_Size() int {
	return xxx_messageInfo_IchZiehAus.Size(m)
}
func (m *IchZiehAus) XXX_DiscardUnknown() {
	xxx_messageInfo_IchZiehAus.DiscardUnknown(m)
}

var xxx_messageInfo_IchZiehAus proto.InternalMessageInfo

func (m *IchZiehAus) GetMyMax() int32 {
	if m != nil {
		return m.MyMax
	}
	return 0
}

type SendMeYourData struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMeYourData) Reset()         { *m = SendMeYourData{} }
func (m *SendMeYourData) String() string { return proto.CompactTextString(m) }
func (*SendMeYourData) ProtoMessage()    {}
func (*SendMeYourData) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{9}
}

func (m *SendMeYourData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMeYourData.Unmarshal(m, b)
}
func (m *SendMeYourData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMeYourData.Marshal(b, m, deterministic)
}
func (m *SendMeYourData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMeYourData.Merge(m, src)
}
func (m *SendMeYourData) XXX_Size() int {
	return xxx_messageInfo_SendMeYourData.Size(m)
}
func (m *SendMeYourData) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMeYourData.DiscardUnknown(m)
}

var xxx_messageInfo_SendMeYourData proto.InternalMessageInfo

type SetYourPID struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetYourPID) Reset()         { *m = SetYourPID{} }
func (m *SetYourPID) String() string { return proto.CompactTextString(m) }
func (*SetYourPID) ProtoMessage()    {}
func (*SetYourPID) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{10}
}

func (m *SetYourPID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetYourPID.Unmarshal(m, b)
}
func (m *SetYourPID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetYourPID.Marshal(b, m, deterministic)
}
func (m *SetYourPID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetYourPID.Merge(m, src)
}
func (m *SetYourPID) XXX_Size() int {
	return xxx_messageInfo_SetYourPID.Size(m)
}
func (m *SetYourPID) XXX_DiscardUnknown() {
	xxx_messageInfo_SetYourPID.DiscardUnknown(m)
}

var xxx_messageInfo_SetYourPID proto.InternalMessageInfo

type PflanzBaum struct {
	Size                 int32    `protobuf:"varint,1,opt,name=Size,json=size,proto3" json:"Size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PflanzBaum) Reset()         { *m = PflanzBaum{} }
func (m *PflanzBaum) String() string { return proto.CompactTextString(m) }
func (*PflanzBaum) ProtoMessage()    {}
func (*PflanzBaum) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{11}
}

func (m *PflanzBaum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PflanzBaum.Unmarshal(m, b)
}
func (m *PflanzBaum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PflanzBaum.Marshal(b, m, deterministic)
}
func (m *PflanzBaum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PflanzBaum.Merge(m, src)
}
func (m *PflanzBaum) XXX_Size() int {
	return xxx_messageInfo_PflanzBaum.Size(m)
}
func (m *PflanzBaum) XXX_DiscardUnknown() {
	xxx_messageInfo_PflanzBaum.DiscardUnknown(m)
}

var xxx_messageInfo_PflanzBaum proto.InternalMessageInfo

func (m *PflanzBaum) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func init() {
	proto.RegisterType((*Insert)(nil), "messages.Insert")
	proto.RegisterType((*Search)(nil), "messages.Search")
	proto.RegisterType((*Traverse)(nil), "messages.Traverse")
	proto.RegisterType((*ScottyBeamMichHoch)(nil), "messages.scottyBeamMichHoch")
	proto.RegisterType((*Delete)(nil), "messages.Delete")
	proto.RegisterType((*DeleteResult)(nil), "messages.DeleteResult")
	proto.RegisterType((*CheckLeftMax)(nil), "messages.CheckLeftMax")
	proto.RegisterType((*BruderMussLos)(nil), "messages.BruderMussLos")
	proto.RegisterType((*IchZiehAus)(nil), "messages.IchZiehAus")
	proto.RegisterType((*SendMeYourData)(nil), "messages.sendMeYourData")
	proto.RegisterType((*SetYourPID)(nil), "messages.setYourPID")
	proto.RegisterType((*PflanzBaum)(nil), "messages.PflanzBaum")
}

func init() { proto.RegisterFile("tree.proto", fileDescriptor_cb3889276909882a) }

var fileDescriptor_cb3889276909882a = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x49, 0xff, 0x84, 0x38, 0xd4, 0x5a, 0x16, 0x91, 0xe2, 0x41, 0xc2, 0x1e, 0xa4, 0xa7,
	0x22, 0xf8, 0x09, 0xac, 0x3d, 0x58, 0x6c, 0xa0, 0xa4, 0x5e, 0xf4, 0xb6, 0x6e, 0x5f, 0x4d, 0x48,
	0xd2, 0x95, 0x9d, 0xdd, 0xd2, 0xf6, 0xd3, 0x4b, 0xda, 0x22, 0x82, 0xb9, 0xcd, 0x6f, 0x66, 0xde,
	0x7b, 0x03, 0x43, 0xe4, 0x2c, 0x30, 0xfe, 0xb6, 0xc6, 0x19, 0x11, 0x55, 0x60, 0x56, 0x5f, 0x60,
	0xf9, 0x40, 0xe1, 0x6c, 0xc3, 0xb0, 0x4e, 0x0c, 0xa8, 0x5d, 0x60, 0x3f, 0x0c, 0xe2, 0x60, 0xd4,
	0x4d, 0xeb, 0x52, 0x5c, 0x53, 0x77, 0xab, 0x4a, 0x8f, 0x61, 0x2b, 0x0e, 0x46, 0x17, 0xe9, 0x09,
	0xe4, 0x2d, 0x85, 0x4b, 0x28, 0xab, 0xb3, 0xff, 0x0a, 0x49, 0x14, 0xbd, 0x59, 0xb5, 0x85, 0x65,
	0xc8, 0x39, 0x09, 0xd6, 0xc6, 0xb9, 0xfd, 0x04, 0xaa, 0x4a, 0x72, 0x9d, 0xbd, 0x98, 0x26, 0x4d,
	0x73, 0x8a, 0xe8, 0x53, 0xcb, 0x14, 0xc3, 0x76, 0x1c, 0x8c, 0xa2, 0xb4, 0x65, 0x8a, 0x3a, 0x75,
	0x8a, 0x12, 0x0e, 0x0d, 0xa9, 0x63, 0xea, 0x9d, 0x66, 0x29, 0xd8, 0x97, 0x4e, 0xdc, 0x11, 0xb1,
	0xd7, 0x1a, 0xcc, 0x6b, 0x5f, 0x1e, 0x17, 0xa3, 0xf4, 0x4f, 0x47, 0xde, 0x53, 0xef, 0x39, 0x83,
	0x2e, 0xe6, 0x58, 0xbb, 0x44, 0xed, 0xc4, 0x0d, 0x85, 0x95, 0xda, 0xbd, 0xfe, 0x9a, 0x9e, 0x49,
	0x5e, 0xd1, 0xe5, 0xc4, 0xfa, 0x15, 0x6c, 0xe2, 0x99, 0xe7, 0x86, 0xa5, 0x24, 0x9a, 0xe9, 0xec,
	0x23, 0x47, 0xf6, 0xe4, 0xb9, 0x3e, 0xbc, 0xda, 0x27, 0x6a, 0x77, 0x56, 0x9d, 0x40, 0x0e, 0xa8,
	0xcf, 0xd8, 0xac, 0x12, 0xbc, 0x1b, 0x6f, 0xa7, 0xca, 0x29, 0xd9, 0x23, 0x62, 0xb8, 0x1a, 0x17,
	0xb3, 0xa9, 0x8c, 0x89, 0x16, 0xeb, 0x52, 0x6d, 0x0e, 0x13, 0xe5, 0x2b, 0x21, 0xa8, 0xb3, 0xcc,
	0x0f, 0x38, 0x5b, 0x74, 0x38, 0x3f, 0xe0, 0x33, 0x3c, 0xfe, 0xe8, 0xf1, 0x27, 0x00, 0x00, 0xff,
	0xff, 0xbf, 0x68, 0xc9, 0x7d, 0xb1, 0x01, 0x00, 0x00,
}
